language: node_js
sudo: required
node_js:
  - "4.1"
services:
  - docker
install:
  - npm install -g firebase-tools
  - chmod +x build.sh
  - ./build.sh
script:
  - docker-compose ps | grep app
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
